# **EXTRACTION ET ANALYSE DE LA CAPITALISATION DES CRYPTOMONNAIES**
------------------------------------------------------------------------------------------------------------------

    Dans ce projet je vais apprendre a construire un pipeline ETL pour analyser la capitalisation boursiere des cryptomonaie. 
    le processus est le suivant : 

    
        *extration a partir des sources sur intgernet 
        *transformation ou nettoyage et structuration des données
        *chargement dans une base de donner ou sauvegarder sous forme de fichier csv

## PROBLEMATIQUE

**PROBLEMATIQUE**: comment la boursiere des principales cryptomonaies evolue-elle au cour du temps,et peut on observer des tendances clair a partir des volumes de transactions et des variations de prix.

## OBJECTIF: 
    l'objectif de ce projet est d'extraire des donnéess de capitalisation boursieres des principales cryptomonaies sur plusieurs mois/années et d'analyser le volume de la capitalisation boursiere en fonction des transactions. nous allons aussi essayer d'identifier des pic ou des creux dans ces valeur pour comprendre les periodes de forte volatilité.

In [ ]:

#installation des pakages necessaires pour le projet ETL 
#ce pakage permet de faire des requetes HTTP pour extraire les données d'une API bref du scraping de données

! pip install requests

Defaulting to user installation because normal site-packages is not writeable
Collecting requests
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.6-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
Downloading charset_normalizer-3.4.6-cp312-cp312-win_amd64.whl (154 kB)
Downloading idna-3.11-py3-none-any.whl (71 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests
Successfully installed certifi-2026.2.25 charset_normalizer-3.4.6 idna-3.11 requests-2.33.1 urllib3-2.6.3

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

### EXTRACTION OU SACAPPING

In [3]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\loica\appdata\roaming\python\python312\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\loica\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\loica\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.7 MB 699.0 kB/s eta 0:00:14
   -- ------------------------------------- 0.5/9.7 MB 699.0 kB/s eta 0:00:14
   --- ------------------------------------ 0.8/9.7 MB 713.3 kB/s eta 0:00:13
   ---- ----------------------------------- 1.0/9.7 MB 786.4 kB/s eta 0:00:12
   ----- ---------------------------------- 1.3/9.7 MB 798.6 kB/s eta 0:00:11
   ------ --------------------------------- 1.6/9.7 MB 838.6 kB/s eta 0:00:10
   ------- -------------------------------- 1.8/9.7 MB 890.6 kB/s eta 0:00:09
   ------- -------------------------------- 1.8/9.7 MB 890.6 kB/s eta 0:00:09
   -------- ------------------------------- 2.1/9.7 MB 917.5 kB/s eta 0:00:09
   --------- ------------------------------ 2.4/9.7 MB 938.3 kB/s eta 0:00:08
   ---------- ----------------------------- 2.6/9.7 MB 920.5 kB/s eta 0:00:08
   ----------- ---------------------------- 2.9/9.7 MB 947.7 kB/s eta 0:00:08
   ------------ --------------------------- 3.1/9.7 MB 956.1 kB/s eta 0:00:07
   ------------ --------------------------- 3.1/9.7 MB 956.1 kB/s eta 0:00:07
   ------------- -------------------------- 3.4/9.7 MB 945.2 kB/s eta 0:00:07
   --------------- ------------------------ 3.7/9.7 MB 931.9 kB/s eta 0:00:07
   --------------- ------------------------ 3.7/9.7 MB 931.9 kB/s eta 0:00:07
   ---------------- ----------------------- 3.9/9.7 MB 928.4 kB/s eta 0:00:07
   ----------------- ---------------------- 4.2/9.7 MB 932.0 kB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.7 MB 925.5 kB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.7 MB 925.5 kB/s eta 0:00:06
   ------------------- -------------------- 4.7/9.7 MB 925.9 kB/s eta 0:00:06
   -------------------- ------------------- 5.0/9.7 MB 906.9 kB/s eta 0:00:06
   -------------------- ------------------- 5.0/9.7 MB 906.9 kB/s eta 0:00:06
   --------------------- ------------------ 5.2/9.7 MB 897.9 kB/s eta 0:00:06
   --------------------- ------------------ 5.2/9.7 MB 897.9 kB/s eta 0:00:06
   ---------------------- ----------------- 5.5/9.7 MB 890.0 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 889.6 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 889.6 kB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.7 MB 885.1 kB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.7 MB 885.1 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.7 MB 865.2 kB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.7 MB 856.7 kB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.7 MB 856.7 kB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.7 MB 859.5 kB/s eta 0:00:04
   ----------------------------- ---------- 7.1/9.7 MB 862.0 kB/s eta 0:00:04
   ------------------------------ --------- 7.3/9.7 MB 874.5 kB/s eta 0:00:03
   ------------------------------ --------- 7.3/9.7 MB 874.5 kB/s eta 0:00:03
   ------------------------------- -------- 7.6/9.7 MB 865.1 kB/s eta 0:00:03
   ------------------------------- -------- 7.6/9.7 MB 865.1 kB/s eta 0:00:03
   -------------------------------- ------- 7.9/9.7 MB 849.1 kB/s eta 0:00:03
   -------------------------------- ------- 7.9/9.7 MB 849.1 kB/s eta 0:00:03
   --------------------------------- ------ 8.1/9.7 MB 841.6 kB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.7 MB 845.6 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.7 MB 849.5 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.7 MB 855.7 kB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.7 MB 855.7 kB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.7 MB 855.7 kB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 838.9 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 835.2 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 835.2 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 821.7 kB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 814.6 kB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.2 tzdata-2025.3

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
# importation des pakages necessaires pour le projet ETL
import requests
import pandas as pd

In [5]:
# l'etape c'est l'ex traction des données d'une API
# on va utiliser l'API coingecko pour extraire les données sur les cryptomonnaies
# on aura besoin de l'url de l'API coingecko pour extraire les données sur les crypt

url="https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false"
parameters={
    "vs_currency":"usd",
    "order":"market_cap_desc",
    "per_page":10000,    #obtenier les 10000 premiers résultats 
    "page":1,
    "sparkline":False
}

#requette de l'API coingecko pour extraire les données sur les cryptomonnaies
response=requests.get(url,params=parameters)

#verifier si la requette a reussi en affichant le code de status de la reponse

if response.status_code==200:
    data = response.json()  # convertir la reponse en format json pour pouvoir l'utiliser dans le projet ETL
    df = pd.json_normalize(data)  # convertir les données en format de tableau pour pouvoir les utiliser dans le projet ETL
else:
    raise Exception(f"Erreur lors de la requette de l'API coingecko: {response.status_code}")  # afficher un message d'erreur si la requette a echoué

In [6]:
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated,roi.times,roi.currency,roi.percentage
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,68123.000000,1363044519310,1,1363044519310,5.508772e+10,68286.000000,...,-45.96872,2025-10-06T18:57:42.558Z,6.781000e+01,1.003624e+05,2013-07-06T00:00:00.000Z,NaN,2026-03-31T22:57:44.720Z,NaN,NaN,NaN
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2093.890000,252648615172,2,252648615172,2.121776e+10,2114.720000,...,-57.66528,2025-08-24T19:21:03.333Z,4.329790e-01,4.835023e+05,2015-10-20T00:00:00.000Z,NaN,2026-03-31T22:57:44.838Z,40.093657,btc,4009.365718
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999106,184071141477,3,189533603443,8.238512e+10,0.999225,...,-24.48180,2018-07-24T00:00:00.000Z,5.725210e-01,7.452247e+01,2015-03-02T00:00:00.000Z,NaN,2026-03-31T22:57:44.616Z,NaN,NaN,NaN
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,616.530000,84075640144,4,84075640144,1.110375e+09,618.510000,...,-54.99782,2025-10-13T08:41:24.131Z,3.981770e-02,1.548272e+06,2017-10-19T00:00:00.000Z,NaN,2026-03-31T22:57:44.331Z,NaN,NaN,NaN
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.330000,81999983334,5,133519318058,2.022172e+09,1.350000,...,-63.39034,2025-07-18T03:40:53.808Z,2.686210e-03,4.959560e+04,2014-05-22T00:00:00.000Z,NaN,2026-03-31T22:57:44.370Z,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,fetch-ai,fet,Artificial Superintelligence Alliance,https://coin-images.coingecko.com/coins/images...,0.231487,522766843,96,628327395,8.839641e+07,0.236563,...,-93.31057,2024-03-28T17:21:18.050Z,8.169590e-03,2.728327e+03,2020-03-13T02:24:18.347Z,NaN,2026-03-31T22:57:45.647Z,1.669982,usd,166.998171
96,bonk,bonk,Bonk,https://coin-images.coingecko.com/coins/images...,0.000006,513816164,97,513816164,3.581364e+07,0.000006,...,-89.99165,2024-11-20T04:01:06.465Z,8.614200e-08,6.667720e+03,2022-12-29T22:48:46.755Z,NaN,2026-03-31T22:57:43.520Z,NaN,NaN,NaN
97,true-usd,tusd,TrueUSD,https://coin-images.coingecko.com/coins/images...,0.997706,493355626,98,493355626,9.480643e+06,0.998309,...,-38.36944,2018-08-26T20:41:09.375Z,8.835500e-01,1.289668e+01,2020-03-12T10:47:51.380Z,NaN,2026-03-31T22:57:40.383Z,NaN,NaN,NaN
98,a7a5,a7a5,A7A5,https://coin-images.coingecko.com/coins/images...,0.012323,483067873,99,483067873,1.077250e+03,0.012324,...,-94.63303,2025-08-14T23:03:39.275Z,1.048000e-05,1.175265e+05,2025-08-21T17:38:27.654Z,NaN,2026-03-31T22:57:41.616Z,NaN,NaN,NaN
99,pancakeswap-token,cake,PancakeSwap,https://coin-images.coingecko.com/coins/images...,1.390000,475070770,103,493353659,2.697985e+07,1.400000,...,-96.84529,2021-04-30T10:08:22.934Z,1.944410e-01,6.133060e+02,2020-11-03T14:29:34.165Z,NaN,2026-03-31T22:57:37.735Z,NaN,NaN,NaN

In [8]:
# afficher les informations sur le dataframe pour pouvoir les utiliser dans le projet ETL

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 29 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                100 non-null    str
 1   symbol                            100 non-null    str
 2   name                              100 non-null    str
 3   image                             100 non-null    str
 4   current_price                     100 non-null    float64
 5   market_cap                        100 non-null    int64
 6   market_cap_rank                   100 non-null    int64
 7   fully_diluted_valuation           100 non-null    int64
 8   total_volume                      100 non-null    float64
 9   high_24h                          100 non-null    float64
 10  low_24h                           100 non-null    float64
 11  price_change_24h                  100 non-null    float64
 12  price_change_percentage_24h       100 non-null    float64
 13  market_cap_change_24h             100 non-null    float64
 14  market_cap_change_percentage_24h  100 non-null    float64
 15  circulating_supply                100 non-null    float64
 16  total_supply                      100 non-null    float64
 17  max_supply                        53 non-null     float64
 18  ath                               100 non-null    float64
 19  ath_change_percentage             100 non-null    float64
 20  ath_date                          100 non-null    str
 21  atl                               100 non-null    float64
 22  atl_change_percentage             100 non-null    float64
 23  atl_date                          100 non-null    str
 24  roi                               0 non-null      float64
 25  last_updated                      100 non-null    str
 26  roi.times                         11 non-null     float64
 27  roi.currency                      11 non-null     str
 28  roi.percentage                    11 non-null     float64
dtypes: float64(18), int64(3), str(8)
memory usage: 22.8 KB

### EN ENTREPRISES EN AS BESOIN D'ENCAPSULER LE RESULTATS PRECEDENT AFIN DE L'AUTOMATISER ON PROCEDE AINSI

In [9]:
def extract_data_from_coingecko():
    url = "https://api.coingecko.com/api/v3/coins/markets"
    parameters = {
        "vs_currency": "usd",
        "order": "market_cap_desc",
        "per_page": 10000,
        "page": 1,
        "sparkline": False
    }
    response = requests.get(url, params=parameters)
    if response.status_code == 200:
        data = response.json()
        df = pd.json_normalize(data)
        return df
    else:
        raise Exception(f"Erreur lors de la requette de l'API coingecko: {response.status_code}")

In [ ]:
#resultat final de l'extraction des données de l'API coingecko
df_crypto = extract_data_from_coingecko() #afficher les informations sur le dataframe pour pouvoir les utiliser dans le projet ETL
df_crypto.info()
df_crypto.shape    #peremet de voir le nombre de lignes et de colonnes du dataframe pour pouvoir les utiliser dans le projet ETL

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 29 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                100 non-null    str
 1   symbol                            100 non-null    str
 2   name                              100 non-null    str
 3   image                             100 non-null    str
 4   current_price                     100 non-null    float64
 5   market_cap                        100 non-null    int64
 6   market_cap_rank                   100 non-null    int64
 7   fully_diluted_valuation           100 non-null    int64
 8   total_volume                      100 non-null    float64
 9   high_24h                          100 non-null    float64
 10  low_24h                           100 non-null    float64
 11  price_change_24h                  100 non-null    float64
 12  price_change_percentage_24h       100 non-null    float64
 13  market_cap_change_24h             100 non-null    float64
 14  market_cap_change_percentage_24h  100 non-null    float64
 15  circulating_supply                100 non-null    float64
 16  total_supply                      100 non-null    float64
 17  max_supply                        53 non-null     float64
 18  ath                               100 non-null    float64
 19  ath_change_percentage             100 non-null    float64
 20  ath_date                          100 non-null    str
 21  atl                               100 non-null    float64
 22  atl_change_percentage             100 non-null    float64
 23  atl_date                          100 non-null    str
 24  roi                               0 non-null      float64
 25  last_updated                      100 non-null    str
 26  roi.times                         11 non-null     float64
 27  roi.currency                      11 non-null     str
 28  roi.percentage                    11 non-null     float64
dtypes: float64(18), int64(3), str(8)
memory usage: 22.8 KB

(100, 29)

### TRANSFORMATION DES DONNES

Premiere transformation ,Nous allos retirer les colones inutiles afin de ne conserver que celle qui serons interessante pour notre anlyse

In [11]:
df_transformed = df_crypto[["id", "symbol", "name", "current_price", "market_cap", "total_volume", "price_change_percentage_24h", "last_updated"]]

In [12]:
df_transformed

,id,symbol,name,current_price,market_cap,total_volume,price_change_percentage_24h,last_updated
0,bitcoin,btc,Bitcoin,68168.000000,1362443267868,5.569688e+10,2.64217,2026-03-31T23:08:40.729Z
1,ethereum,eth,Ethereum,2095.340000,252657285981,2.117407e+10,3.96185,2026-03-31T23:08:41.084Z
2,tether,usdt,Tether,0.999125,184058366576,8.222109e+10,-0.00797,2026-03-31T23:08:36.040Z
3,binancecoin,bnb,BNB,616.760000,84048607081,1.111340e+09,1.54505,2026-03-31T23:08:40.738Z
4,ripple,xrp,XRP,1.330000,81940603139,2.008821e+09,0.97955,2026-03-31T23:08:35.674Z
...,...,...,...,...,...,...,...,...
95,fetch-ai,fet,Artificial Superintelligence Alliance,0.231116,521832085,8.961309e+07,1.49692,2026-03-31T23:08:36.076Z
96,bonk,bonk,Bonk,0.000006,513828736,3.567163e+07,0.71330,2026-03-31T23:08:38.663Z
97,true-usd,tusd,TrueUSD,0.997484,493320726,8.817060e+06,-0.02835,2026-03-31T23:08:35.989Z
98,a7a5,a7a5,A7A5,0.012324,483079638,1.077280e+03,0.75590,2026-03-31T23:08:35.857Z
99,pancakeswap-token,cake,PancakeSwap,1.390000,474721742,2.679407e+07,0.64920,2026-03-31T23:08:36.323Z

In [13]:
#deuxieme transformation renommer les colonnes du dataframe 

df_transformed.columns = ["id", "symbol", "name", "price_usd", "market_cap_usd", "volume_24h_usd", "price_change_percentage_24h", "date"]
df_transformed

,id,symbol,name,price_usd,market_cap_usd,volume_24h_usd,price_change_percentage_24h,date
0,bitcoin,btc,Bitcoin,68168.000000,1362443267868,5.569688e+10,2.64217,2026-03-31T23:08:40.729Z
1,ethereum,eth,Ethereum,2095.340000,252657285981,2.117407e+10,3.96185,2026-03-31T23:08:41.084Z
2,tether,usdt,Tether,0.999125,184058366576,8.222109e+10,-0.00797,2026-03-31T23:08:36.040Z
3,binancecoin,bnb,BNB,616.760000,84048607081,1.111340e+09,1.54505,2026-03-31T23:08:40.738Z
4,ripple,xrp,XRP,1.330000,81940603139,2.008821e+09,0.97955,2026-03-31T23:08:35.674Z
...,...,...,...,...,...,...,...,...
95,fetch-ai,fet,Artificial Superintelligence Alliance,0.231116,521832085,8.961309e+07,1.49692,2026-03-31T23:08:36.076Z
96,bonk,bonk,Bonk,0.000006,513828736,3.567163e+07,0.71330,2026-03-31T23:08:38.663Z
97,true-usd,tusd,TrueUSD,0.997484,493320726,8.817060e+06,-0.02835,2026-03-31T23:08:35.989Z
98,a7a5,a7a5,A7A5,0.012324,483079638,1.077280e+03,0.75590,2026-03-31T23:08:35.857Z
99,pancakeswap-token,cake,PancakeSwap,1.390000,474721742,2.679407e+07,0.64920,2026-03-31T23:08:36.323Z

In [14]:
#transformer la colone date pour qu 'elle soit au format datetime pour pouvoir l'utiliser par l'equipe de data analyste
df_transformed["date"] = pd.to_datetime(df_transformed["date"]).dt.date
df_transformed

,id,symbol,name,price_usd,market_cap_usd,volume_24h_usd,price_change_percentage_24h,date
0,bitcoin,btc,Bitcoin,68168.000000,1362443267868,5.569688e+10,2.64217,2026-03-31
1,ethereum,eth,Ethereum,2095.340000,252657285981,2.117407e+10,3.96185,2026-03-31
2,tether,usdt,Tether,0.999125,184058366576,8.222109e+10,-0.00797,2026-03-31
3,binancecoin,bnb,BNB,616.760000,84048607081,1.111340e+09,1.54505,2026-03-31
4,ripple,xrp,XRP,1.330000,81940603139,2.008821e+09,0.97955,2026-03-31
...,...,...,...,...,...,...,...,...
95,fetch-ai,fet,Artificial Superintelligence Alliance,0.231116,521832085,8.961309e+07,1.49692,2026-03-31
96,bonk,bonk,Bonk,0.000006,513828736,3.567163e+07,0.71330,2026-03-31
97,true-usd,tusd,TrueUSD,0.997484,493320726,8.817060e+06,-0.02835,2026-03-31
98,a7a5,a7a5,A7A5,0.012324,483079638,1.077280e+03,0.75590,2026-03-31
99,pancakeswap-token,cake,PancakeSwap,1.390000,474721742,2.679407e+07,0.64920,2026-03-31

In [15]:
# la derniere transfo c'est de remplacer toutes les valeuur manquantes par des 0 pour que l'equipe de data analyste puisse utiliser les données sans avoir des erreurs de valeurs manquantes
df_transformed.fillna(0, inplace=True)
df_transformed

,id,symbol,name,price_usd,market_cap_usd,volume_24h_usd,price_change_percentage_24h,date
0,bitcoin,btc,Bitcoin,68168.000000,1362443267868,5.569688e+10,2.64217,2026-03-31
1,ethereum,eth,Ethereum,2095.340000,252657285981,2.117407e+10,3.96185,2026-03-31
2,tether,usdt,Tether,0.999125,184058366576,8.222109e+10,-0.00797,2026-03-31
3,binancecoin,bnb,BNB,616.760000,84048607081,1.111340e+09,1.54505,2026-03-31
4,ripple,xrp,XRP,1.330000,81940603139,2.008821e+09,0.97955,2026-03-31
...,...,...,...,...,...,...,...,...
95,fetch-ai,fet,Artificial Superintelligence Alliance,0.231116,521832085,8.961309e+07,1.49692,2026-03-31
96,bonk,bonk,Bonk,0.000006,513828736,3.567163e+07,0.71330,2026-03-31
97,true-usd,tusd,TrueUSD,0.997484,493320726,8.817060e+06,-0.02835,2026-03-31
98,a7a5,a7a5,A7A5,0.012324,483079638,1.077280e+03,0.75590,2026-03-31
99,pancakeswap-token,cake,PancakeSwap,1.390000,474721742,2.679407e+07,0.64920,2026-03-31

In [16]:
# pour automatiser le processus d'extraction et de transformation des données de l'API coingecko 
# on va creer une fonction qui va faire tout le processus d'extraction et de transformation des données
#  de l'API coingecko pour pouvoir l'utiliser dans le projet ETL
def transform_data(df):
    df_transformed = df[["id", "symbol", "name", "current_price", "market_cap", "total_volume", "price_change_percentage_24h", "last_updated"]]
    df_transformed.columns = ["id", "symbol", "name", "price_usd", "market_cap_usd", "volume_24h_usd", "price_change_percentage_24h", "date"]
    df_transformed["date"] = pd.to_datetime(df_transformed["date"]).dt.date
    df_transformed.fillna(0, inplace=True)
    return df_transformed

In [17]:
#affichage de la base de donne transformee par automatisation

df_transformed_auto = transform_data(df_crypto)
df_transformed_auto

,id,symbol,name,price_usd,market_cap_usd,volume_24h_usd,price_change_percentage_24h,date
0,bitcoin,btc,Bitcoin,68168.000000,1362443267868,5.569688e+10,2.64217,2026-03-31
1,ethereum,eth,Ethereum,2095.340000,252657285981,2.117407e+10,3.96185,2026-03-31
2,tether,usdt,Tether,0.999125,184058366576,8.222109e+10,-0.00797,2026-03-31
3,binancecoin,bnb,BNB,616.760000,84048607081,1.111340e+09,1.54505,2026-03-31
4,ripple,xrp,XRP,1.330000,81940603139,2.008821e+09,0.97955,2026-03-31
...,...,...,...,...,...,...,...,...
95,fetch-ai,fet,Artificial Superintelligence Alliance,0.231116,521832085,8.961309e+07,1.49692,2026-03-31
96,bonk,bonk,Bonk,0.000006,513828736,3.567163e+07,0.71330,2026-03-31
97,true-usd,tusd,TrueUSD,0.997484,493320726,8.817060e+06,-0.02835,2026-03-31
98,a7a5,a7a5,A7A5,0.012324,483079638,1.077280e+03,0.75590,2026-03-31
99,pancakeswap-token,cake,PancakeSwap,1.390000,474721742,2.679407e+07,0.64920,2026-03-31

In [ ]:
df_transformed_auto.to_csv("data_transformed.csv", index=False)

#permet d'enregistrer le dataframe transformé dans un fichier csv

### CHARGEMENT DES DONNES DANS UNE BASE DE DONNE SQL

In [20]:
! pip install postgreSQL

Defaulting to user installation because normal site-packages is not writeable

ERROR: Could not find a version that satisfies the requirement postgreSQL (from versions: none)

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for postgreSQL

In [22]:
import postgresql

#conn = postgresql.open()
def load_data_to_postgresql(df,db_file,table_name):
    conn = postgresql.open('postgresql://user:280715@localhost/db_file')
    cursor = conn.cursor()
    # creer la table si elle n'existe pas deja
    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS {table_name} (
            id TEXT PRIMARY KEY,
            symbol TEXT,
            name TEXT,
            price_usd REAL,
            market_cap_usd REAL,
            volume_24h_usd REAL,
            price_change_percentage_24h REAL,
            date DATE
        )
    """)
    # inserer les données dans la table
    df.to_sql(table_name, conn, if_exists='append', index=False)
    conn.commit()
    conn.close()
    print(f"Les données ont été chargées avec succès dans la table '{table_name}' de la base de données {db_file}")

#exeple de fichier de base de données postgresql
db_file= 'pluto_database.db'
table_name = 'crypto_data'

#charger les données dans la base de données postgresql
load_data_to_postgresql(df_transformed_auto, db_file, table_name)

ModuleNotFoundError: No module named 'postgresql'

# AUTRE ETL

In [ ]:
!pip install kaggle

In [ ]:
!kaggle datasets list -s "avocado" --sort-by 'votes'

In [ ]:
!kaggle datasets download -d "neuromusic/avocado-prices" -p "/Users/ashwinsingaram/Documents/Kaggle/Avocado""neuromusic/avocado-prices" -p "/Users/ashwinsingaram/Documents/Kaggle/Avocado"

In [ ]:
!pip install --force-reinstall psycopg2

In [ ]:
import psycopg2 
import pandas as pd 
from psycopg2 import extras 

databasename= 'xxxx' 
 username= 'xxxxxx'
 pwd= 'yyyy'
 hostname= 'localhost'
 port_id= '5432' 



try : 
    conn = psycopg2.connect( 
        dbname=databasename, 
        user=username, 
        password=pwd, 
        host=hostname, 
        port=port_id 
    ) 
    cur = conn.cursor() 

    cur.execute( "DROP TABLE IF EXISTS avocsss" ) 

    create_script = """CREATE TABLE avocsss ( 
                        Date DATE, 
                        AveragePrice FLOAT, 
                        TotalVolume FLOAT, 
                        plu_4046 double precision, 
                        plu_4225 double precision, 
                        plu_4770 double precision, 
                        TotalBags FLOAT, 
                        SmallBags FLOAT, 
                        LargeBags FLOAT, 
                        XLargeBags FLOAT, 
                        type VARCHAR(50), 
                        année INT, 
                        région VARCHAR(50), 
                        séquence INT PRIMARY KEY 
                    );"""

     cur.execute(create_script) 
    conn.commit() 
    
    psycopg2.extras.execute_values( 
        cur, 
        """ 
        INSERT INTO avocsss ( 
            Date, AveragePrice, TotalVolume, plu_4046, plu_4225, plu_4770, TotalBags, SmallBags, LargeBags, XLargeBags, type, year, region, sequence 
        ) VALUES %s 
        """ , 
        df.values.tolist() 
    ) 
    conn.commit() 
    
except (Exception, psycopg2.DatabaseError) as error: 
    print ( "Une erreur s'est produite : " , error) 

finally : 
    if conn is  not  None : 
        if cur is  not  None : 
            cur.close() 
        conn.close()